### ISSUE TITLE
When to release the algorithm's code?

### ISSUE THREAD

**Issue by BITminicc** [kikojay/EMC#1]
Awesome work published in NeurIPS 2021. Since you've become the new state-of-the-art, please release the algorithm's code as soon as possible. I am looking forward to some analysis and discussion with this great work!

**Comment by WisdomPK** [comment]
+1, want to follow the code of EMC

**Comment by ZYC9894** [comment]
+1

**Comment by kikojay** [comment]
sorry for the inconvenience, and now I have released the code of EMC.
