### ISSUE TITLE
Import Error: cannot import spread_xEnv

### ISSUE THREAD

**Issue by torelax** [kikojay/EMC#2]
while run python command, it take error
> from smac.env import MultiAgentEnv, StarCraft2Env, Matrix_game1Env, Matrix_game2Env, Matrix_game3Env, mmdp_game1Env, \
 **ImportError: cannot import name 'spread_xEnv' from 'smac.env'**  

there is no EMC_env but EMC_smac_env, and i can't find 'spread_xEnv' in EMC_samc_envs/smac/env

so how to get spread_xEnv or  will it affect the program if I delete it directly?

Looking forward to your reply！

**Comment by kikojay** [comment]
Yes, just removing  `spread_xEnv`  env will be ok. And I have fixed it in the latest commit, you can pull the latest version or delete it directly. Thanks for pointing it out!
