### ISSUE TITLE
What is a proper "unit_dim" value of modified prey and predator to be compatible with qplex algorithm?

### ISSUE THREAD

**Issue by HyunghoNa** [kikojay/EMC#3]
Hello~
Thanks for sharing the nice code. ^^

During implementation, I was wondering what is the right value for "unit_dim" of modified prey and predator.
In the uploaded code, unit_dim is set as 0 which seems not proper for qatten weight calculation.
I couldn't decide the right value for it after briefly read the environment code which is stag_hunt.py.

Could you tell me which value of "unit_dim" was used in modified prey and predator when conducting experiment for qplex or EMC(qplex).. ?

Thank you for your time!

**Comment by kikojay** [comment]
Thanks for your question! QPLEX has two configs in this code base: Qplex_sc2 and Qplex_toygame. You can use the configuration of Qplex_toygame to run **QPLEX** on the prey and predator and the "unit_dim" is not required in the code of Qplex_toygame.

**Comment by HyunghoNa** [comment]
Oh I see. The mixer structures of qplex for toygame and sc2 are different then... okay! Thank you for the answer! :)
